import type { PromptSkill, ProviderServiceConfig, ProviderType, Settings, Template } from '@/shared/types'

export const APP_NAME = 'AI Prompt Enhancer'
export const STORAGE_KEYS = {
  settings: 'ape_settings',
  templates: 'ape_templates',
  history: 'ape_history',
  rules: 'ape_rules',
  skills: 'ape_skills',
  savedPrompts: 'ape_saved_prompts',
  providerConfigs: 'ape_provider_configs',
  providerKeys: 'ape_provider_keys',
  sessionPassphrasePrefix: 'ape_session_passphrase_',
  installId: 'ape_install_id',
} as const

export const SCHEMA_VERSION = 2

export const DEFAULT_SETTINGS: Settings = {
  schemaVersion: SCHEMA_VERSION,
  language: 'zh-CN',
  provider: 'openai',
  defaultSkillId: 'builtin-general-enhancer-skill',
  defaultMode: 'detailed',
  enhancementWorkflow: 'direct',
  outputFormat: 'markdown',
  outputLanguagePolicy: 'followInput',
  historyEnabled: true,
  historyLimit: 200,
  storeSourceText: true,
  detectSensitiveText: true,
  explicitTriggerOnly: true,
  theme: 'light',
  launcher: {
    enabled: true,
    secondaryActionsEnabled: true,
    position: 'above',
    size: 24,
    opacity: 0.92,
    color: '#22c55e',
  },
  modeProviderStrategy: {
    coding: 'openai',
    business: 'anthropic',
    english: 'openai',
  },
}

const now = new Date('2026-07-07T00:00:00.000Z').toISOString()

export const BUILTIN_TEMPLATES: Template[] = [
  {
    id: 'builtin-general',
    title: '通用增强（热门）',
    description: '适合绝大多数 Prompt 优化场景，强调目标、上下文、约束和输出结构。',
    category: '通用',
    mode: 'detailed',
    content:
      '请将我的原始需求重写成一个高质量 Prompt。要求：1）保留原始意图；2）补齐目标、上下文、约束条件、输入输出；3）输出结构清晰；4）如果信息缺失，用 [请补充：xxx] 标记；5）避免空话与套话。',
    usageHint: '适用于日常通用增强、需求整理、任务描述不完整时的二次强化。',
    sourceName: 'f/prompts.chat',
    sourceUrl: 'https://github.com/f/prompts.chat',
    builtin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-code-generation-hot',
    title: '结构化代码生成（热门）',
    description: '适合接口、脚本、组件、页面、自动化任务等高频开发场景。',
    category: '编程',
    mode: 'coding',
    content:
      '请把需求整理成面向工程实现的 Prompt。必须明确：技术栈、目录或模块边界、输入输出、边界条件、异常处理、测试要求、验收标准，以及哪些内容不要实现。若信息不足，请先列出待补充项。',
    usageHint: '适用于“帮我写一个接口 / 页面 / 脚本 / 工具”的开发请求。',
    sourceName: 'dair-ai/Prompt-Engineering-Guide',
    sourceUrl: 'https://github.com/dair-ai/prompt-engineering-guide',
    builtin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-code-review-hot',
    title: '代码审查（热门）',
    description: '适合 Review 代码、PR、补丁、脚本，按严重级别输出问题。',
    category: '编程',
    mode: 'coding',
    content:
      '请作为严格的代码审查助手，按“严重级别 → 问题描述 → 影响 → 证据/复现思路 → 修复建议”的结构输出。重点检查正确性、安全性、边界条件、性能、可维护性、测试缺失和潜在回归风险。',
    usageHint: '适用于代码评审、PR Review、上线前检查、找 bug 和安全问题。',
    sourceName: 'PickleBoxer/dev-chatgpt-prompts',
    sourceUrl: 'https://github.com/PickleBoxer/dev-chatgpt-prompts',
    builtin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-debug-hot',
    title: '报错排查（热门）',
    description: '适合日志、报错、异常栈、失败现象的定位与修复。',
    category: '调试',
    mode: 'stepByStep',
    content:
      '请把问题改写成适合排障的 Prompt，并按“现象 → 复现条件 → 可能根因 → 验证步骤 → 修复方案 → 回归检查”的结构组织输出。优先帮助快速定位，不要泛泛解释。',
    usageHint: '适用于运行报错、接口失败、前端异常、构建失败、测试失败等问题。',
    sourceName: 'danielrosehill/Prompt-Debugger-System-Prompts',
    sourceUrl: 'https://github.com/danielrosehill/Prompt-Debugger-System-Prompts',
    builtin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-readme-hot',
    title: 'README / 技术文档（热门）',
    description: '适合 README、接入文档、方案说明、SOP、部署文档。',
    category: '文档',
    mode: 'detailed',
    content:
      '请把内容整理成专业文档型 Prompt。必须明确目标读者、结构章节、操作步骤、配置项、示例、注意事项、常见问题和验证方式，保证读者可以直接照着执行。',
    usageHint: '适用于项目 README、部署说明、产品接入文档、团队内部 SOP。',
    sourceName: 'brexhq/prompt-engineering',
    sourceUrl: 'https://github.com/brexhq/prompt-engineering',
    builtin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-writing-hot',
    title: '内容创作 / 文案润色（热门）',
    description: '适合公众号、博客、视频脚本、社媒文案、产品介绍。',
    category: '写作',
    mode: 'business',
    content:
      '请把需求增强成适合内容创作的 Prompt，补齐：目标受众、语言风格、篇幅、结构提纲、标题方向、示例、禁忌表达和最终交付格式。输出时保持可读性和传播性。',
    usageHint: '适用于文章、短文案、营销内容、产品介绍、脚本创作。',
    sourceName: 'awesome-chatgpt-prompts/awesome-chatgpt-prompts-github',
    sourceUrl: 'https://github.com/awesome-chatgpt-prompts/awesome-chatgpt-prompts-github',
    builtin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-data-analysis-hot',
    title: '数据分析 / 报表解读（热门）',
    description: '适合 CSV、Excel、实验结果、业务报表、指标分析。',
    category: '分析',
    mode: 'stepByStep',
    content:
      '请把需求整理成面向数据分析的 Prompt，要求模型明确分析目标、关键指标、分析步骤、异常值检查、结论表达方式、图表建议和最终输出格式；若有数据缺口，请先列出。',
    usageHint: '适用于表格分析、运营报表、实验结果解释、业务指标洞察。',
    sourceName: 'dair-ai/Prompt-Engineering-Guide',
    sourceUrl: 'https://github.com/dair-ai/prompt-engineering-guide',
    builtin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-algorithm-explain-hot',
    title: '算法 / 概念讲解（热门）',
    description: '适合面试题、算法解释、论文概念说明、知识点拆解。',
    category: '学习',
    mode: 'detailed',
    content:
      '请把问题增强为适合教学讲解的 Prompt，要求模型按“核心概念 → 直觉理解 → 分步过程 → 示例 → 复杂度/优缺点 → 常见误区”的结构解释，并尽量降低理解门槛。',
    usageHint: '适用于算法题讲解、知识点学习、概念解释、面试复习。',
    sourceName: 'f/prompts.chat',
    sourceUrl: 'https://github.com/f/prompts.chat',
    builtin: true,
    createdAt: now,
    updatedAt: now,
  },
]

const baseProvider = (
  provider: ProviderType,
  label: string,
  baseUrl: string,
  model: string,
  models: string[],
  authMode: ProviderServiceConfig['authMode'] = 'bearer',
): ProviderServiceConfig => ({
  provider,
  label,
  baseUrl,
  model,
  models,
  authMode,
  temperature: 0.4,
  maxTokens: 4096,
  timeoutMs: 90_000,
  retryCount: 2,
  enabled: true,
})

export const DEFAULT_PROVIDER_CONFIGS: ProviderServiceConfig[] = [
  baseProvider('openai', 'OpenAI', 'https://api.openai.com/v1/chat/completions', 'gpt-4.1-mini', [
    'gpt-4.1-mini',
    'gpt-4.1',
    'gpt-4o-mini',
    'gpt-4o',
    'o4-mini',
  ]),
  baseProvider('anthropic', 'Anthropic', 'https://api.anthropic.com/v1/messages', 'claude-3-5-sonnet-latest', [
    'claude-3-5-sonnet-latest',
    'claude-3-7-sonnet-latest',
    'claude-3-5-haiku-latest',
  ], 'x-api-key'),
  baseProvider('gemini', 'Google Gemini', 'https://generativelanguage.googleapis.com/v1beta/models', 'gemini-2.0-flash', [
    'gemini-2.0-flash',
    'gemini-1.5-pro',
    'gemini-1.5-flash',
  ], 'query-key'),
  baseProvider(
    'azureOpenAI',
    'Azure OpenAI',
    'https://YOUR_RESOURCE.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT/chat/completions?api-version=2024-10-21',
    'gpt-4.1-mini',
    ['gpt-4.1-mini', 'gpt-4o-mini'],
    'api-key',
  ),
  baseProvider('ollama', 'Ollama', 'http://127.0.0.1:11434/api/chat', 'qwen2.5:7b', ['qwen2.5:7b', 'llama3.1:8b'], 'none'),
  baseProvider('deepseek', 'DeepSeek', 'https://api.deepseek.com/chat/completions', 'deepseek-v4-flash', ['deepseek-v4-flash', 'deepseek-v4-pro']),
  baseProvider('moonshot', 'Moonshot / Kimi', 'https://api.moonshot.cn/v1/chat/completions', 'moonshot-v1-8k', ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k']),
  baseProvider('qwen', 'DashScope Qwen', 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions', 'qwen-plus', ['qwen-turbo', 'qwen-plus', 'qwen-max', 'qwen2.5-72b-instruct']),
  baseProvider('zhipu', 'Zhipu GLM', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', 'glm-4-flash', ['glm-4-flash', 'glm-4-air', 'glm-4-plus']),
  baseProvider('siliconflow', 'SiliconFlow', 'https://api.siliconflow.cn/v1/chat/completions', 'Qwen/Qwen2.5-72B-Instruct', ['Qwen/Qwen2.5-72B-Instruct', 'deepseek-ai/DeepSeek-V3', 'deepseek-ai/DeepSeek-R1']),
  baseProvider('volcengine', 'Volcengine Ark / Doubao', 'https://ark.cn-beijing.volces.com/api/v3/chat/completions', 'doubao-seed-1-6-flash-250615', ['doubao-seed-1-6-flash-250615', 'doubao-1.5-lite-32k-250115', 'doubao-1.5-pro-32k-250115']),
  baseProvider('custom', 'Custom Compatible Endpoint', '', 'gpt-4.1-mini', ['gpt-4.1-mini']),
]

const skillVersion = (version: string, description: string, promptTemplate: string) => ({
  versionId: crypto.randomUUID(),
  version,
  updatedAt: now,
  description,
  promptTemplate,
  variables: [],
  triggerConditions: [],
})

export const BUILTIN_PROMPT_SKILLS: PromptSkill[] = [
  {
    id: 'builtin-general-enhancer-skill',
    name: 'General Prompt Enhancer Skill',
    description: 'Default general Skill. It preserves user intent and fills in context, constraints, output format, and acceptance criteria.',
    tags: ['general', 'prompt-engineering', 'default'],
    author: 'AI Prompt Enhancer',
    repoUrl: 'https://github.com/openai/openai-cookbook',
    version: '1.0.0',
    updatedAt: '2026-07-08T00:00:00.000Z',
    promptTemplate:
      'Rewrite the user input into a high-quality prompt that can be sent directly to an AI model. Preserve the original intent, add missing context, constraints, inputs, outputs, and acceptance criteria. If information is missing, mark it as [Please provide: xxx] instead of inventing it. Original input:\n{{input}}',
    variables: [],
    triggerConditions: ['Default enhancement', 'General clarification', 'Need a fuller and more robust prompt'],
    intentRequirements: ['goal', 'expectedOutput', 'constraints', 'acceptanceCriteria'],
    enabled: true,
    builtin: true,
    rating: 4.9,
    usageCount: 0,
    sourceType: 'builtin-github',
    versions: [
      skillVersion(
        '1.0.0',
        'Default general enhancement skill',
        'Rewrite the user input into a high-quality prompt that can be sent directly to an AI model. Preserve the original intent, add missing context, constraints, inputs, outputs, and acceptance criteria. If information is missing, mark it as [Please provide: xxx] instead of inventing it. Original input:\n{{input}}',
      ),
    ],
  },
  {
    id: 'github-copilot-prompt-patterns',
    name: 'Code Generation Skill',
    description: '面向代码生成任务，强调语言/框架、输入输出、边界条件和测试要求。',
    tags: ['code', 'generation', 'engineering'],
    author: 'GitHub Community',
    repoUrl: 'https://github.com/github/awesome-copilot',
    version: '1.0.0',
    updatedAt: '2026-06-28T00:00:00.000Z',
    promptTemplate:
      '请扮演资深工程师，根据以下需求生成可运行代码，并明确技术栈、输入输出、边界条件、测试方法和验收标准：\n{{input}}',
    variables: [],
    triggerConditions: ['当用户需求包含“实现”“生成代码”“写函数”时推荐'],
    intentRequirements: ['goal', 'technicalStack', 'inputs', 'expectedOutput', 'constraints', 'acceptanceCriteria'],
    enabled: true,
    builtin: true,
    rating: 4.8,
    usageCount: 0,
    sourceType: 'builtin-github',
    versions: [
      skillVersion(
        '1.0.0',
        '初始版本',
        '请扮演资深工程师，根据以下需求生成可运行代码，并明确技术栈、输入输出、边界条件、测试方法和验收标准：\n{{input}}',
      ),
    ],
  },
  {
    id: 'github-code-review-skill',
    name: 'Code Review Skill',
    description: '面向代码审查，输出风险、缺陷、性能、可维护性及修复建议。',
    tags: ['code-review', 'quality', 'security'],
    author: 'GitHub Community',
    repoUrl: 'https://github.com/microsoft/prompt-engine',
    version: '1.2.0',
    updatedAt: '2026-06-21T00:00:00.000Z',
    promptTemplate:
      '请作为严谨的 Reviewer，对以下代码或改动进行审查，按严重级别列出问题、影响、复现/证据和修复建议：\n{{input}}',
    variables: [],
    triggerConditions: ['当用户需求包含 review、审查、找问题、PR 时推荐'],
    intentRequirements: ['goal', 'inputs', 'constraints', 'expectedOutput'],
    enabled: true,
    builtin: true,
    rating: 4.7,
    usageCount: 0,
    sourceType: 'builtin-github',
    versions: [
      skillVersion(
        '1.2.0',
        '增加安全与测试维度',
        '请作为严谨的 Reviewer，对以下代码或改动进行审查，按严重级别列出问题、影响、复现/证据和修复建议：\n{{input}}',
      ),
    ],
  },
  {
    id: 'github-doc-writing-skill',
    name: 'Documentation Writing Skill',
    description: '面向技术文档、README、设计说明和操作手册撰写。',
    tags: ['docs', 'writing', 'developer-experience'],
    author: 'GitHub Community',
    repoUrl: 'https://github.com/openai/openai-cookbook',
    version: '0.9.0',
    updatedAt: '2026-06-10T00:00:00.000Z',
    promptTemplate:
      '请将以下需求或草稿整理为结构清晰的技术文档，明确目标、步骤、配置、验证和注意事项：\n{{input}}',
    variables: [],
    triggerConditions: ['文档撰写、README、SOP、知识库更新'],
    intentRequirements: ['goal', 'audience', 'context', 'expectedOutput', 'acceptanceCriteria'],
    enabled: true,
    builtin: true,
    rating: 4.6,
    usageCount: 0,
    sourceType: 'builtin-github',
    versions: [
      skillVersion(
        '0.9.0',
        '初始版本',
        '请将以下需求或草稿整理为结构清晰的技术文档，明确目标、步骤、配置、验证和注意事项：\n{{input}}',
      ),
    ],
  },
  {
    id: 'github-debug-assistant-skill',
    name: 'Debug Assistant Skill',
    description: '面向报错定位、复现、根因分析和修复策略。',
    tags: ['debug', 'bugfix', 'troubleshooting'],
    author: 'GitHub Community',
    repoUrl: 'https://github.com/microsoft/promptbase',
    version: '1.1.0',
    updatedAt: '2026-06-12T00:00:00.000Z',
    promptTemplate:
      '请分析以下报错/现象，按“复现条件 → 根因假设 → 验证步骤 → 修复方案 → 回归检查”输出：\n{{input}}',
    variables: [],
    triggerConditions: ['当用户输入包含 error、报错、失败、异常、debug 时推荐'],
    intentRequirements: ['goal', 'context', 'inputs', 'constraints', 'expectedOutput'],
    enabled: true,
    builtin: true,
    rating: 4.8,
    usageCount: 0,
    sourceType: 'builtin-github',
    versions: [
      skillVersion(
        '1.1.0',
        '增加回归检查',
        '请分析以下报错/现象，按“复现条件 → 根因假设 → 验证步骤 → 修复方案 → 回归检查”输出：\n{{input}}',
      ),
    ],
  },
  {
    id: 'github-algorithm-explainer-skill',
    name: 'Algorithm Explainer Skill',
    description: '面向算法解释、复杂度分析和示例推导。',
    tags: ['algorithm', 'education', 'explanation'],
    author: 'GitHub Community',
    repoUrl: 'https://github.com/karpathy/llm.c',
    version: '1.0.1',
    updatedAt: '2026-05-30T00:00:00.000Z',
    promptTemplate:
      '请把以下算法或思路解释清楚，包含核心概念、关键步骤、复杂度、示例和常见误区：\n{{input}}',
    variables: [],
    triggerConditions: ['算法解释、面试题讲解、教学场景'],
    intentRequirements: ['goal', 'audience', 'inputs', 'expectedOutput'],
    enabled: true,
    builtin: true,
    rating: 4.5,
    usageCount: 0,
    sourceType: 'builtin-github',
    versions: [
      skillVersion(
        '1.0.1',
        '增加常见误区',
        '请把以下算法或思路解释清楚，包含核心概念、关键步骤、复杂度、示例和常见误区：\n{{input}}',
      ),
    ],
  },
]
